# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memorymonitor.ui'
#
# Created: Wed May  1 22:48:21 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MemoryMonitor(object):
    def setupUi(self, MemoryMonitor):
        MemoryMonitor.setObjectName("MemoryMonitor")
        MemoryMonitor.resize(672, 471)
        self.horizontalLayout = QtGui.QHBoxLayout(MemoryMonitor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(MemoryMonitor)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.virtChart = Chart(self.groupBox)
        self.virtChart.setObjectName("virtChart")
        self.verticalLayout_2.addWidget(self.virtChart)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.labelVirtTotal = QtGui.QLabel(self.groupBox)
        self.labelVirtTotal.setText("")
        self.labelVirtTotal.setObjectName("labelVirtTotal")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelVirtTotal)
        self.labelVirtAvailable = QtGui.QLabel(self.groupBox)
        self.labelVirtAvailable.setText("")
        self.labelVirtAvailable.setObjectName("labelVirtAvailable")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelVirtAvailable)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_8)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.labelVirtUsed = QtGui.QLabel(self.groupBox)
        self.labelVirtUsed.setText("")
        self.labelVirtUsed.setObjectName("labelVirtUsed")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.labelVirtUsed)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_11)
        self.labelVirtFree = QtGui.QLabel(self.groupBox)
        self.labelVirtFree.setText("")
        self.labelVirtFree.setObjectName("labelVirtFree")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.labelVirtFree)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(MemoryMonitor)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.swapChart = Chart(self.groupBox_2)
        self.swapChart.setEnabled(True)
        self.swapChart.setObjectName("swapChart")
        self.verticalLayout.addWidget(self.swapChart)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.labelSwapTotal = QtGui.QLabel(self.groupBox_2)
        self.labelSwapTotal.setText("")
        self.labelSwapTotal.setObjectName("labelSwapTotal")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelSwapTotal)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.labelSwapAvailable = QtGui.QLabel(self.groupBox_2)
        self.labelSwapAvailable.setText("")
        self.labelSwapAvailable.setObjectName("labelSwapAvailable")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelSwapAvailable)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.labelSwapUsed = QtGui.QLabel(self.groupBox_2)
        self.labelSwapUsed.setText("")
        self.labelSwapUsed.setObjectName("labelSwapUsed")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.labelSwapUsed)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.labelSwapFree = QtGui.QLabel(self.groupBox_2)
        self.labelSwapFree.setText("")
        self.labelSwapFree.setObjectName("labelSwapFree")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.labelSwapFree)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(MemoryMonitor)
        QtCore.QMetaObject.connectSlotsByName(MemoryMonitor)

    def retranslateUi(self, MemoryMonitor):
        MemoryMonitor.setWindowTitle(QtGui.QApplication.translate("MemoryMonitor", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MemoryMonitor", "RAM usage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MemoryMonitor", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MemoryMonitor", "Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MemoryMonitor", "Available:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MemoryMonitor", "Used:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MemoryMonitor", "Free:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MemoryMonitor", "Swap usage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MemoryMonitor", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MemoryMonitor", "Available:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MemoryMonitor", "Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MemoryMonitor", "Used:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MemoryMonitor", "Free:", None, QtGui.QApplication.UnicodeUTF8))

from app.chart import Chart
